In [7]:
a = [
    [1, 2, 3], 
    [4, 5, 6]]

a * 2

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [9]:
# NumPy 설치
!pip install numpy

In [11]:
import numpy

a = [1, 2, 3, 4, 5, 6]
print('a: ', a)
print(type(a))
b = numpy.array(a)
print('b: ', b)
print(type(b))

a:  [1, 2, 3, 4, 5, 6]
<class 'list'>
b:  [1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [13]:
import numpy as np

np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [19]:
np.array('dataedu')

array('dataedu', dtype='<U7')

In [14]:
np.arange(7) # range(7)


array([0, 1, 2, 3, 4, 5, 6])

In [16]:
np.arange(1, 6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [18]:
# 파이썬 내장함수 range()
list(range(1, 6, 2))

[1, 3, 5]

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [26]:
np.full(5, 4).dtype

dtype('int64')

In [27]:
np.full(5, 4.).dtype

dtype('float64')

In [28]:
np.full(5, 4, dtype='float').dtype

dtype('float64')

In [30]:
# 2차원 배열

# 2행 5열
np.array([
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 10]
])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [31]:
# 3행 3열

np.array([
    [1, 2, 3], 
    [4, 5 ,6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.ones((2, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.zeros((2, 5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
np.full((2, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [40]:
# 3차원 배열

np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]
     ],
     [[2, 4, 6, 8],
      [10, 12, 14, 16]
      ], 
      [[1, 3, 5, 7],
       [9, 11, 13, 15]]
])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]]])

In [39]:
np.ones((3, 2, 4), dtype='int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [41]:
np.zeros((3, 2, 4), dtype='int')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [42]:
np.full((3, 2, 4), 5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [47]:
# 1차원
arr_1d = np.array([1, 2, 3, 4])

# 2차원
arr_2d = np.array([
                    [1, 2, 3, 4], 
                    [5, 6, 7, 8]
                ])

# 3차원
arr_3d = np.array([
                    [
                        [1, 2, 3, 4], 
                        [5, 6, 7, 8]
                        ],
                    [
                        [2, 4, 6, 8],
                        [10, 12, 14, 16]
                    ],
                    [
                        [1, 3, 5, 7],
                        [9, 11, 13, 15]
                    ]
                    ])

In [48]:
arr_1d.shape

(4,)

In [49]:
arr_2d.shape

(2, 4)

In [50]:
arr_3d.shape

(3, 2, 4)

In [51]:
arr_1d.size

4

In [52]:
arr_2d.size

8

In [53]:
arr_3d.size

24

In [54]:
arr_1d.ndim

1

In [58]:
arr_2d.ndim

2

In [57]:
arr_3d.ndim

3